<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ooc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~O</string>
	<key>name</key>
	<string>ooc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#imports</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interface_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cover_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_call</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#member_access</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.block.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member_access</string>
				</dict>
			</array>
		</dict>
		<key>class_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.abstract.ooc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.ooc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.type.generic.ooc</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.class.ooc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?mx)
            ([_A-Z]\w* \s*) : \s* (abstract\s+)? (class)
            (?:
                \s*&lt;\s*([^&lt;]+)\s*&gt;\s*
            )?
		   (?:
                \s* (extends)
            )?
            </string>
			<key>name</key>
			<string>meta.class.ooc</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.block.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^/\* =(\s*.*?)\s*= \*/$\n?</string>
					<key>name</key>
					<string>comment.block.ooc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ooc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*/.*\n</string>
					<key>name</key>
					<string>invalid.illegal.stray-comment-end.ooc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.line.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^// =(\s*.*?)\s*=\s*$\n?</string>
					<key>name</key>
					<string>comment.line.banner.ooc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ooc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.ooc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&gt;\\\s*\n)</string>
							<key>name</key>
							<string>punctuation.separator.continuation.ooc</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>cover_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cover.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.cover.ooc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.from.ooc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.overtype.ooc</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.cover.ooc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.supertype.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?mx)
            ([_A-Z]\w* \s*) : \s* (cover)
            (?:
            (?:
                \s+(from)\s+(?:([\s\w\d_\*]+?)\s*(?= \s extends | [/{;] | $) )
            )
            |
            (?:
                \s+(extends)\s+([_A-Z]\w*)\s*
            )
            )*
            </string>
			<key>name</key>
			<string>meta.definition.cover.ooc</string>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.ooc</string>
		</dict>
		<key>function_call</key>
		<dict>
			<key>begin</key>
			<string>(?:((?:\.[a-z_]\w*)|(?:[a-z_]\w*)(?:~[a-z_]\w*)?))\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method.ooc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.function.call.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#member_access</string>
				</dict>
			</array>
		</dict>
		<key>function_decl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?mx)
            	        (operator\s+(?:(?:[+\-/\*=!&lt;&gt;]|\[\])=?|\[\]|[&lt;&gt;=]|=|as))
        	            [\s\w~]*?
        	            \(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.ooc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?mx)\)

        			(?:\s*(-&gt;) \s*
        		    (?:
						(?:(This) |
        		        ([A-Z_]\w*))
        		        ([@*]*)
        		    ))?</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.return-type.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.this.ooc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.ooc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.operator.ooc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?mx)
        		        ([_a-z]\w*) \s* : \s*
        		            ((?:(?:static|proto|inline|final|abstract)\s+)*)
        		            (?:(extern|unmangled)(?:\s*\(([^\)]+)\))?\s+
        		                ((?:(?:static|proto|inline|final|abstract)\s+)*)
        		            )?
        		            
        		            (func)
							
							(?:\s*@)?
							
        		            (?:\s*(~[A-Za-z_]\w*))?
                        
                            (?:
                                \s*&lt;\s*([^&lt;]+)\s*&gt;
                            )?
                            
        		            \s* \(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.ooc</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>storage.type.ooc</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.ooc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.extern.ooc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.function.c</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.ooc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.ooc</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.func-tag.ooc</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>support.type.generic.ooc</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>keyword.other.return-type.ooc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?mx)\)
					(?:\s*(-&gt;) \s*
        		    (?:
						(?:(This) | 
        		        ([A-Z_]\w*))
        		        ([@*]*)
        		    ))?</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.this.ooc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.ooc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.params.ooc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.ooc</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.this.ooc</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>storage.type.ooc</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.ooc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.extern.ooc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.function.c</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.ooc</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.ooc</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.func-tag.ooc</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>support.type.generic.ooc</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>keyword.other.return-type.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?mx)
        		        ([_a-z]\w*) \s* : \s*
        		            
        		            ((?:(?:static|proto|inline|final|abstract)\s+)*)
        		            (?:(extern|unmangled)(?:\s*\(([^\)]+)\))?\s+
        		                ((?:(?:static|proto|inline|final|abstract)\s+)*)
        		            )?
        		            
        		            (func)

        		            (?:\s*(~[A-Za-z_]\w*))?
                        
                            (?:
                                \s*&lt;\s*([^&lt;]+)\s*&gt;
                            )?
                            
                            (?:\s*(-&gt;) \s*
                		    (?:
								(?:(This) |
                		        ([A-Z_]\w*))
                		        ([@*]*)
                		    ))?
        		            </string>
					<key>name</key>
					<string>meta.function.noparams.ooc</string>
				</dict>
			</array>
		</dict>
		<key>imports</key>
		<dict>
			<key>begin</key>
			<string>\b(?:use|include|import)\b</string>
			<key>end</key>
			<string>;|$</string>
			<key>name</key>
			<string>keyword.control.import.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>interface_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.abstract.ooc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.ooc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.type.generic.ooc</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.class.ooc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?mx)
            ([_A-Z]\w* \s*) : \s* (interface)
            (?:
                \s*&lt;\s*([^&lt;]+)\s*&gt;\s*
            )?
            </string>
			<key>name</key>
			<string>meta.interface.ooc</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:if|else|while|do|for|in|switch|match|case|return|break|continue|default)\b</string>
					<key>name</key>
					<string>keyword.control.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bthis\b</string>
					<key>name</key>
					<string>variable.language.this.ooc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.class.this.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(This)([@&amp;*]*|\b)</string>
					<key>name</key>
					<string>meta.type.class.this.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:&amp;&amp;|\|\||\#|!)</string>
					<key>name</key>
					<string>keyword.operator.logical.ooc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#return_type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:[&lt;&gt;!=]=|=&gt;|[&gt;&lt;])</string>
					<key>name</key>
					<string>keyword.operator.comparison.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:[\*+\-/|&amp;:]|&lt;{2,3}|&gt;{2,3})?=</string>
					<key>name</key>
					<string>keyword.operator.assignment.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:[\*\-\+/|&amp;]|&lt;{2,3}|&gt;{2,3})</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:true|false)\b</string>
					<key>name</key>
					<string>constant.language.boolean.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bnull\b</string>
					<key>name</key>
					<string>constant.language.null.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bconst\b</string>
					<key>name</key>
					<string>keyword.other.directive.const.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bstatic\b</string>
					<key>name</key>
					<string>keyword.other.directive.static.ooc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.as.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.ooc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(as)\s*([A-Z_]\w*)([@&amp;]*)</string>
					<key>name</key>
					<string>meta.operator.as.ooc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(Func)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.pointer.ooc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.function.pointer.ooc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.pointer.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?mx)\bFunc\b</string>
					<key>name</key>
					<string>meta.function.pointer.ooc</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ooc_numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ooc_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ooc_string</string>
				</dict>
			</array>
		</dict>
		<key>member_access</key>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_]\w*)\s+(?=[a-zA-Z_])</string>
			<key>name</key>
			<string>variable.other.accessed.ooc</string>
		</dict>
		<key>ooc_char</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<key>ooc_numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(0c[0-7]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.octal.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(0x[0-9a-fA-F]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.hexadecimal.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(0b[01]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.binary.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x) (?&lt;! 0[bcx] ) (
                            (?: (?:[0-9]*)\.(?:[0-9]+) | (?:[0-9]+)\.(?:[0-9]*) )
                            (?: [eE][+\-]?\d+)?
                        )</string>
					<key>name</key>
					<string>constant.numeric.float.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)\b([0-9]+)(?: [eE][+\-]?\d+)?</string>
					<key>name</key>
					<string>constant.numeric.integer.ooc</string>
				</dict>
			</array>
		</dict>
		<key>ooc_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([_A-Z]\w*)([&amp;@*]*)</string>
					<key>name</key>
					<string>meta.function.nameless-typed.ooc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.pointer-arith.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>:\s*([A-Z_]\w*([@&amp;*]*))</string>
					<key>name</key>
					<string>meta.function.parameter.type.ooc</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.parameter.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([=.])?([a-zA-Z_]\w*)</string>
					<key>name</key>
					<string>meta.function.parameter.name.ooc</string>
				</dict>
			</array>
		</dict>
		<key>return_type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.return-type.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.this.ooc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.ooc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.pointer-arith.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?mx)
		    (\-\&gt;) \s*
		    (?:
				(?:(This) |
		        ([A-Z_]\w*))
		        ([@*]*)
		    )</string>
			<key>name</key>
			<string>meta.function.return-type.ooc</string>
		</dict>
		<key>var_explicit_decl</key>
		<dict>
			<key>begin</key>
			<string>[_a-zA-Z]\w*\s*(?=,|:[^=])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.ooc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?mx)(?:
			(?:
			    :\s*
			    (?:
			        (?:
			            (?:
			                (static) |
			                (const) |
			                (extern) (?:\s* \( \s* ([^\)]+) \s* \) )?
			            ) \s+
			        )*
                )
			    (?: (?: (This) | ([A-Z_]\w*)) ([@&amp;]*) )
				(?: \s* \&lt;\s*([A-Z_]\w*)\s*\&gt; )?
			) | ; | $ )</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ooc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.ooc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.c</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.this.ooc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.ooc</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.pointer-arith.ooc</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>support.type.generic.ooc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.variable.explicit.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[_a-zA-Z]\w*</string>
					<key>name</key>
					<string>variable.other.ooc</string>
				</dict>
			</array>
		</dict>
		<key>var_inferred_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)([a-zA-Z_]\w*)\s*(?= := )</string>
			<key>name</key>
			<string>meta.definition.variable.inferred.ooc</string>
		</dict>
		<key>variable_decl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#var_inferred_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var_explicit_decl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ooc</string>
	<key>uuid</key>
	<string>EECF47FE-041D-4F42-B64C-414A1EFD807F</string>
</dict>
</plist>
