<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ooc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~O</string>
	<key>name</key>
	<string>ooc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#class_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cover_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable_decl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ooc_numbers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.block.occ</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ooc_numbers</string>
				</dict>
			</array>
		</dict>
		<key>class_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cover.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.abstract.ooc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.ooc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.generic.ooc</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.cover.ooc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cover.supertype.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?mx)
            ([_A-Z]\w* \s*) : \s* (abstract\s+)? (class)
            (?:
                \s*&lt;\s*([^&lt;]+)\s*&gt;\s*
            )?
            (?:
                \s+(extends)\s+([_A-Z]\w*)
            )?
            </string>
			<key>name</key>
			<string>meta.class.ooc</string>
		</dict>
		<key>cover_decl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cover.ooc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.cover.ooc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.from.ooc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cover.overtype.ooc</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.extends.cover.ooc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cover.supertype.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?mx)
            ([_A-Z]\w* \s*) : \s* (cover)
            (?:
            (?:
                \s+(from)\s+(.+?(?= \s extends | { | $) )
            )
            |
            (?:
                \s+(extends)\s+([_A-Z]\w*)
            )
            )*
            </string>
			<key>name</key>
			<string>meta.definition.cover.ooc</string>
		</dict>
		<key>function_decl</key>
		<dict>
			<key>name</key>
			<string>meta.function.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?mx)
        		        ([_a-z]\w*) \s* : \s*
        		            (?:(extern)(?:\(([^\)]+)\))?\s+)?
        		            (func) \s*
        		            (?:(~[a-z_]\w*)\s*)?

        		            (?: \( )?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.directive.ooc</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.extern.ooc</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.ooc</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.meta.ooc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?mx)(\)|(?=\{)|$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable_decl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|while|do|for|in|switch|match|case|)\b</string>
				</dict>
			</array>
		</dict>
		<key>ooc_char</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.ooc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>'(\.|.)'</string>
			<key>name</key>
			<string>meta.constant.character.ooc</string>
		</dict>
		<key>ooc_numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(0c[0-7]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.octal.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(0x[0-9a-fA-F]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.hexadecimal.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(0b[01]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.binary.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x) (?&lt;! 0[bcx] ) (
                            (?: (?:\d*)\.(?:\d+) | (?:\d+)\.(?:\d*) )
                        )</string>
					<key>name</key>
					<string>constant.numeric.float.ooc</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)\b([0-9]+)</string>
					<key>name</key>
					<string>constant.numeric.integer.ooc</string>
				</dict>
			</array>
		</dict>
		<key>ooc_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ooc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ooc</string>
				</dict>
			</array>
		</dict>
		<key>variable_decl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[_a-zA-Z]\w*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.other.register.ooc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>:\s*(?:(static)\s+)?([A-Z_]\w*[@&amp;]*)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.directive.global.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.ooc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.variable.local.ooc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[_a-zA-Z]\w*</string>
							<key>name</key>
							<string>variable.other.register.ooc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.register.ooc</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.ooc</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)([a-zA-Z_]\w*)\s*(?= := )</string>
					<key>name</key>
					<string>meta.definition.variable.local.ooc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ooc</string>
	<key>uuid</key>
	<string>EECF47FE-041D-4F42-B64C-414A1EFD807F</string>
</dict>
</plist>
